config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.room_detail, name="detail"),
    path("search/", views.search, name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view() , name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("<int:pk>/", views.ProfileView.as_view(), name="profile")
]

templates/partials/footer.html
<footer class="py-10 mx-auto border-t flex flex-col items-center text-gray-500">
    <h3>Thanks for choosing us</h3> 
    &copy; Nbnb
</footer>

templates/partials/header.html
<header>
    <a href="{% url "core:home" %}">Nbnb</a>
    <nav>
        <ul>
            <a href="#">Login</a>
            <a href="/admin">Admin</a>
            <a href="#">Contacts</a>
        </ul>
    </nav>
    <form method="get" action="{% url "rooms:search" %}">
        <input type="text" name="city" id="" placeholder="Search">
    </form>
</header>

templates/partials/messages.html
{% if messages %}
<ul class="absolute mx-auto left-0 flex-col items-center messages top-2 right-0 z-10 flex justify-center">
    {% for message in messages %}
        <li class="font-medium message px-3 py-2 mb-2 opacity-8 bg-gray-300 text-sm text-gray-700 rounded-lg {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
{% load static %}
<nav class="flex h-full items-center text-sm font-medium">
    {% if user.is_authenticated %}
        <a href="{{user.get_absolute_url}}" class="nav_link">Profile</a>
        <a class="nav_link" href="{% url "users:logout" %}">Logout</a>
    {%else %}
        <a class="nav_link" href="{% url "users:login" %}">Login</a>
        <a class="nav_link" href="{% url "users:signup" %}">Sign up</a> 
    {% endif %}
    
    <a class="nav_link" href="/admin">Admin</a>
    <a class="nav_link" href="#">Contacts</a>
</nav> 

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn border-gray-700 bg-gray-900 hover:bg-white hover:text-gray-900 text-white"> <i class="fab fa-github mr-1"></i> Continue with GitHub</a>
    <a href="#" class="btn border-yellow-300 bg-yellow-300 hover:bg-white hover:text-yellow-400 text-yellow-800"> <i class="fas fa-comment mr-1"></i> Continue with Kakao</a> 
</div>
<div class="w-full flex items-center my-2">
    <div class="w-full h-px bg-gray-300"></div>
    <span class="font-medium text-gray-500 text-sm mx-4">or</span>
    <div class="w-full h-px bg-gray-300"></div>
</div>