config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.room_detail, name="detail"),
    path("search/", views.search, name="search"),
]

templates/mixins/room_card.html
<a href="{% url "rooms:detail" room.pk %}" class="w-1/4 mb-10 px-2">
    <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image: url('{{room.first_photo}}') "></div>
    <div class="flex justify-between mb-px ">
        <div class="">
            {% if room.host.superhost %}
                <span class="uppercase mr-px text-xs border rounded border-black text-black font-medium px-1 py-px">superhost</span> 
            {% endif %}
            <span class="font-normal text-gray-600 text-sm"> {{room.country.name}}, {{room.city}}</span>
        </div>
        <span class="text-sm flex items-center">
            <i class="fas fa-star text-red-500  mr-1 text-xs"></i> {{room.review_avg}}
        </span>
    </div>
    <span class="text-black block truncate w-11/12">{{room.name}}</span>

</a>
  